---
acc_ports:
  - range: "Ethernet1/0 - 3"
    voice: "{{ voice_vlan_01 }}"
    data: "{{ data_vlan_01 }}"

trunk_ports:
 - range: "Ethernet0/0 - 1"
   allowed:
   - "{{ voice_vlan_01 }}"
   - "{{ data_vlan_01 }}"