---
svi_int:
  - name: vlan15
    ip: "{{ vlan15.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252 
    pri: "{{ vlan15.pri }}"

  - name: vlan16 
    ip: "{{ vlan16.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan16.pri }}"

  - name: vlan17
    ip: "{{ vlan17.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan17.pri }}"

  - name: vlan18
    ip: "{{ vlan18.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan18.pri }}"

  - name: vlan55
    ip: "{{ vlan55.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan55.pri }}"
    
  - name: vlan55
    ip: "{{ vlan55.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan55.pri }}"

  - name: vlan56
    ip: "{{ vlan56.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan56.pri }}"
    
  - name: vlan57
    ip: "{{ vlan57.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan57.pri }}"

  - name: vlan58
    ip: "{{ vlan58.ip }}"
    mask: 255.255.255.0
    vip: 10.0.15.252
    pri: "{{ vlan58.pri }}"
    
ptp_links:
  - name: "Ethernet1/0"
    desc: "{{ e10.desc }}"
    ip: "{{ e10.ip }}"
    mask: 255.255.255.252

  - name: "Ethernet1/1"
    desc: "{{ e11.desc }}"
    ip: "{{ e11.ip }}"   
    mask: 255.255.255.252

  - name: "Ethernet1/2"
    desc: "{{ e12.desc }}"
    ip: "{{ e12.ip }}"   
    mask: 255.255.255.252

  - name: "Ethernet2/0"
    desc: "{{ e20.desc }}"
    ip: "{{ e20.ip }}"   
    mask: 255.255.255.252

trunk_ports:
 - range: "Ethernet0/0 - 3"
 
root_bri:
  - id: 15
    role: "{{ vlan15.root }}"
  - id: 16
    role: "{{ vlan16.root }}"
  - id: 17
    role: "{{ vlan17.root }}"
  - id: 18
    role: "{{ vlan18.root }}"
  - id: 55
    role: "{{ vlan55.root }}"
  - id: 56
    role: "{{ vlan56.root }}"
  - id: 57
    role: "{{ vlan57.root }}"
  - id: 58
    role: "{{ vlan58.root }}"
    