---
vlans:
  - { vlan_id: 15, name: voice15}  
  - { vlan_id: 16, name: voice16}
  - { vlan_id: 17, name: voice17}  
  - { vlan_id: 18, name: voice18}  
  - { vlan_id: 55, name: data55}
  - { vlan_id: 56, name: data56}
  - { vlan_id: 57, name: data57}
  - { vlan_id: 58, name: data58}  

trunk_range: e0/0 - 3
trunk_int:
 - Ethernet0/0
 - Ethernet0/1
 - Ethernet0/2 
 - Ethernet0/3 
