---
- name: core switch configurations
  hosts: core
  gather_facts: no
  connection: local


  tasks:

    #
  - name: set hostname
    ios_config:
      provider: "{{ provider }}"
      lines: hostname "{{ ansible_hostname }}"
    tags: hostname

    #
  - name: create vlans
    ios_config:
      provider: "{{ provider }}"
      lines:
      - name {{ item.name }}
      parents: vlan {{ item.vlan_id }}
    with_items: "{{ vlans }}"
    tags: vlans
    
    #
  - name: set trunk port
    ios_config:
      provider: "{{ provider }}"
      lines:
      - switchport trunk encapsulation dot1q
      parents: interface range {{ item }}
    with_items: "{{ trunk_ports }}"
    tags: trunk

    #
  - name: set root brige
    ios_config:
      provider: "{{ provider }}"
      lines:
      - spanning-tree vlan {{ item.id }} root {{ item.role }}
    with_items: "{{ root_bri }}"
    tags: stp

    #
  - name: switch virtual interface
    ios_config:
      provider: "{{ provider }}"
      lines:
      - ip address {{ item.ip }} {{ item.mask }}
      - delay 200
      parents: interface {{ item.name }}
    with_items: "{{ svi_int }}"
    tags: svi
    
    #
  - name: hsrp
    ios_config:
      provider: "{{ provider }}"
      lines:
      - standby 1 ip {{ item.vip }}
      - standby 1 timer msec 250 msec 750
      - standby 1 priority {{ item.pri }}
      - standby 1 preempt delay minimum 30
      parents: interface {{ item.name }}
      match: exact
    with_items: "{{ svi_int }}"
    tags: hsrp
    
    #   
  - name: point-to-point link
    ios_config:
      provider: "{{ provider }}"
      lines:
      - no switchport
      - description {{ item.desc }}
      - ip add {{ item.ip }} {{ item.mask }}
      parents: interface {{ item.name}}
    with_items: "{{ ptp_int }}"
    tags: ptp

    #
  - name: eigrp
    ios_config:
      provider: "{{ provider }}"
      lines:
      - no auto
      - network 10.0.0.0 0.0.255.255
      - passive-interface default
      parents: router eigrp 1
      match: exact
    tags: eigrp

    #
  - name: passive-interface
    ios_config:
      provider: "{{ provider }}"
      lines: 
      - no passive-interface {{ item.name }} 
      parents: router eigrp 1
      match: exact
    with_items: "{{ svi_int }}"
    tags: passive
  - name: passive-interface
    ios_config:
      provider: "{{ provider }}"
      lines: 
      - no passive-interface {{ item.name }} 
      parents: router eigrp 1
      match: exact
    with_items: "{{ ptp_int }}"
    tags: passive
    

    #
  - name: summary route
    ios_config:
      provider: "{{ provider }}"
      lines:
      - ip summary-address eigrp 1 10.0.0.0 255.255.224.0
      - ip summary-address eigrp 1 10.0.32.0 255.255.224.0
      parents: interface {{ item.name }}
      match: exact
    with_items: "{{ ptp_int }}"
    tags: summary