---
- name: core switch configurations
  hosts: routers
  gather_facts: no
  connection: local
 
  tasks:
  

  - name: set hostname
    ios_config:
      provider: "{{ provider }}"
      lines: hostname "{{ ansible_hostname }}"    


  - name: configure interface
    ios_config:
      provider: "{{ provider }}"
      lines:
      - description {{ item.desc }}
      - ip add {{ item.ip }} {{ item.mask }}
      - ip nat inside
      parents: interface {{ item.key }}
    with_items: "{{ int }}"
    tags: int   

    
  - name: configure wan interface
    ios_config:
      provider: "{{ provider }}"
      lines:
      - ip add dhcp
      - ip nat outside
      parents: interface {{ item.name }}
      match: exact            
    with_items: "{{ wan_int }}" 
    tags: wan

    
  - name: access list to use in nat
    ios_config:
      provider: "{{ provider }}"
      lines:
      - permit 10.0.0.0 0.0.63.255 log
      parents: ip access-list standard NAT
      match: exact
    tags: acl
    
    
  - name: access list to use in nat
    ios_config:
      provider: "{{ provider }}"
      lines:
      - permit 10.0.0.0 0.0.63.255 log
      parents: ip access-list standard NAT
      match: exact
    tags: acl


  - name: ip nat and default route
    ios_config:
      provider: "{{ provider }}"
      lines:
      - ip nat inside source list NAT interface {{ item.name }}  overload 
      - ip route 0.0.0.0 0.0.0.0 192.168.91.2
      match: exact
    with_items: "{{ wan_int }}"            
    tags: nat_default
    
    
  - name: routing
    ios_config:
      provider: "{{ provider }}"
      lines:
      - no auto 
      - network 10.0.0.0 0.0.255.255
      - passive-interface default
      - redistribute static
      parents: router eigrp 1
      match: exact            
    tags: routing

  - name: passive interface
    ios_config:
      provider: "{{ provider }}"
      lines:
      - no passive-interface {{ item.name }}
      parents: router eigrp 1
    with_items: "{{ int }}"
    tags: passive