---
- name: core switch configurations
  hosts: routers
  gather_facts: no
  connection: local
 
  tasks:
  
########  
  - name: set hostname
    ios_config:
      provider: "{{ provider }}"
      lines: hostname "{{ ansible_hostname }}"     

########
  - name: configure interface
    ios_config:
      provider: "{{ provider }}"
      lines:
      - description {{ item.value.desc }}
      - ip add {{ item.value.ip }} {{ item.value.mask }}
      - ip nat inside
      parents: interface {{ item.key }}
    with_dict: "{{ int }}"
    tags: int     

########
  - name: configure wan interface
    ios_config:
      provider: "{{ provider }}"
      lines:
      - ip add dhcp
      - ip nat outside
      parents: interface {{ item.key }}
      match: exact            
    with_dict: "{{ wan_int }}" 
    tags: wan

########
  - name: access list to use in nat
    ios_config:
      provider: "{{ provider }}"
      lines:
      - permit 10.0.0.0 0.0.63.255 log
      parents: ip access-list standard NAT
      match: exact
    tags: acl

########
  - name: ip nat and default route
    ios_config:
      provider: "{{ provider }}"
      lines:
      - ip nat inside source list NAT interface e1/0 overload 
      - ip route 0.0.0.0 0.0.0.0 192.168.91.2
      match: exact            
    tags: nat_default

########
  - name: routing
    ios_config:
      provider: "{{ provider }}"
      lines:
      - no auto 
      - network 10.0.0.0 0.0.255.255
      - passive-interface default
      - redistribute static
      parents: router eigrp 1
      match: exact            
    tags: routing
    
########
  - name: passive
    ios_config:
      provider: "{{ provider }}"
      lines:
      - no passive-interface {{ item.key }}
      parents: router eigrp 1
    with_dict: "{{ int }}"
    tags: passive