svi_add:
  - { ip: 192.168.11.252, mask: 255.255.255.0 }
  - { ip: 192.168.12.252, mask: 255.255.255.0 }
  - { ip: 192.168.13.252, mask: 255.255.255.0 }
  - { ip: 192.168.14.252, mask: 255.255.255.0 }
  - { ip: 192.168.51.252, mask: 255.255.255.0 }
  - { ip: 192.168.52.252, mask: 255.255.255.0 }
  - { ip: 192.168.53.252, mask: 255.255.255.0 }
  - { ip: 192.168.54.252, mask: 255.255.255.0 }

routed_ports_add:
  - { description: --> core_sw_02, ip: 172.16.0.1, mask: 255.255.255.0 }
  - { description: --> rtr_01, ip: 172.16.1.1, mask: 255.255.255.0 }
  - { description: --> rtr-02, ip: 172.16.2.1, mask: 255.255.255.0 }

root_bri:
 - { vlan_id: 11, root: primary }
 - { vlan_id: 12, root: primary }
 - { vlan_id: 13, root: primary }
 - { vlan_id: 14, root: primary }
 - { vlan_id: 51, root: secondary }
 - { vlan_id: 52, root: secondary }
 - { vlan_id: 53, root: secondary }
 - { vlan_id: 54, root: secondary }

hsrp_active:
 - { interface: vlan11, pri: 110,}
 - { interface: vlan12, pri: 110 }
 - { interface: vlan13, pri: 110 }
 - { interface: vlan14, pri: 110 }
