---
attr:
 15:
  ip: 10.0.15.252
  hsrp_pri: 110
  root: primary
 16:
  ip: 10.0.16.252
  hsrp_pri: 110
  root: primary
 17:
  ip: 10.0.17.252
  hsrp_pri: 100
  root: secondary
 18:
  ip: 10.0.18.252
  hsrp_pri: 100
  root: secondary
 55:
  ip: 10.0.55.252
  hsrp_pri: 110
  root: primary
 56:
  ip: 10.0.56.252
  hsrp_pri: 110
  root: primary
 57:
  ip: 10.0.57.252
  hsrp_pri: 100
  root: secondary
 58:
  ip: 10.0.58.252
  hsrp_pri: 100
  root: secondary
 e10:
   desc: link-to-core_sw_02
   ip: 10.0.100.1
 e20:
   desc: link-to-core_sw_02
   ip: 10.0.100.21
 e11:
   desc: link-to-rtr_01
   ip: 10.0.100.5
   mask: 255.255.255.252
 e12:
   desc: link-to-rtr_02
   ip: 10.0.100.9